### ISSUE TITLE
Deprecation warnings thrown in CI

### ISSUE THREAD

**Issue by kurtmckee** [codespell-project/sort-problem-matcher#3]
A new version needs to be released to support Node 16. The code appears to be in place already, so all that seems to be needed is a new version.

Other projects are seeing warnings in CI caused by the `v1` tag still requiring Node 12, which is no longer available. Here's [a recent example](https://github.com/codespell-project/codespell/actions/runs/5652805505) from codespell's CI.

I don't have a recommendation whether this should be a new `v1` or should jump to `v2`, but a new version is needed.

**Comment by DimitriPapadopoulos** [comment]
![node12](https://github.com/codespell-project/sort-problem-matcher/assets/3234522/36c8ea62-93e1-4ce2-88ea-256b7f238241)

**Comment by DimitriPapadopoulos** [comment]
* [GitHub Actions: All Actions will run on Node16 instead of Node12](https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/)

**Comment by DimitriPapadopoulos** [comment]
I'll bump from `node16` to `node20` before trying to prepare a `v2`, so that it lasts longer.

**Comment by kurtmckee** [comment]
Friendly ping. :grinning:

**Comment by DimitriPapadopoulos** [comment]
@kurtmckee The version has been bumped from `node16` to `node20` in #5, and is part of [v1.2.0](https://github.com/codespell-project/sort-problem-matcher/releases/tag/v1.2.0). What would be missing?

**Comment by kurtmckee** [comment]
Ah, I had thought that this was only to be released with v2 based on the above discussion.

Only thing missing is for me to close this issue! :grinning: :partying_face:
